find_path(GMOCK_INCLUDE_DIRS NAMES gmock.h HINTS $ENV{GMOCK_HOME} ${GMOCK_HOME} PATH_SUFFIXES include/gmock)
find_path(GTEST_INCLUDE_DIRS NAMES gtest.h HINTS $ENV{GMOCK_HOME} ${GMOCK_HOME} PATH_SUFFIXES gtest/include/gtest)

if(GMOCK_INCLUDE_DIRS)
	set(GMOCK_INCLUDE_DIRS "${GMOCK_INCLUDE_DIRS}/..")
	set(GMOCK_PATH "${GMOCK_INCLUDE_DIRS}/..")
	set(GMOCK_BUILD_PATH "${GMOCK_PATH}/build")
endif()

if(GTEST_INCLUDE_DIRS)
	set(GTEST_INCLUDE_DIRS "${GTEST_INCLUDE_DIRS}/..")
endif()

if(${CMAKE_BUILD_TYPE} STREQUAL "Release")
	set(GMOCK_PATH_SUFFIXES "Release")
else()
	set(GMOCK_PATH_SUFFIXES "Debug")
endif()

find_library(GMOCK_LIBRARY "gmock" HINTS ${GMOCK_BUILD_PATH} PATH_SUFFIXES ${GMOCK_PATH_SUFFIXES})
find_library(GMOCK_LIBRARY_MAIN "gmock_main" HINTS ${GMOCK_BUILD_PATH} PATH_SUFFIXES ${GMOCK_PATH_SUFFIXES})

set(GMOCK_LIBRARIES ${GMOCK_LIBRARY})

