find_path(SDL2_INCLUDE_DIRS NAMES SDL.h HINTS $ENV{SDL2_HOME} ${SDL2_HOME} PATH_SUFFIXES include)

if(SDL2_INCLUDE_DIRS)
	set(SDL2_PATH "${SDL2_INCLUDE_DIRS}/..")
	set(SDL2_BUILD_PATH "${SDL2_PATH}/build")
endif()

if(${CMAKE_BUILD_TYPE} STREQUAL "Release")
	set(SDL2_PATH_SUFFIXES "Release")
else()
	set(SDL2_PATH_SUFFIXES "Debug")
endif()

find_library(SDL2_LIBRARY "SDL2" HINTS ${SDL2_BUILD_PATH} PATH_SUFFIXES ${SDL2_PATH_SUFFIXES})
find_library(SDL2_LIBRARY_MAIN "SDL2main" HINTS ${SDL2_BUILD_PATH} PATH_SUFFIXES ${SDL2_PATH_SUFFIXES})
find_file(SDL2_LIBRARY_SHARED "SDL2.dll" HINTS ${SDL2_BUILD_PATH} PATH_SUFFIXES ${SDL2_PATH_SUFFIXES})

set(SDL2_LIBRARIES ${SDL2_LIBRARY} ${SDL2_LIBRARY_MAIN})

